### ISSUE TITLE
String exception

### ISSUE THREAD

**Issue by pmrogala** [aleripe/AnonymousId#2] opened 2017-12-06 13:37 UTC
Hello,
I'm getting this error:

`
String reference not set to an instance of a String.
Parameter name: s
System.ArgumentNullException: String reference not set to an instance of a String.
Parameter name: s
   at System.Text.Encoding.GetBytes(String s)
   at ReturnTrue.AspNetCore.Identity.Anonymous.AnonymousIdEncoder.Encode(AnonymousIdData data)
   at ReturnTrue.AspNetCore.Identity.Anonymous.AnonymousIdMiddleware.HandleRequest(HttpContext httpContext)
   at ReturnTrue.AspNetCore.Identity.Anonymous.AnonymousIdMiddleware.<Invoke>d__3.MoveNext()
`

**Comment by aleripe** [comment] 2018-08-27 13:28
Hi progala2, do you still need help for the exception?

**Comment by NerijusD** [comment] 2018-09-03 07:18
@aleripe I am getting the same error. Actually this is really bad error, because it breaks every edpoint on the server.

https://www.screencast.com/t/GVeRA0BjOdo

Probably it isn't easy to reproduce, because it happened only after running several days or at least a day. It may do something with expiration date.

**Comment by aleripe** [comment] 2018-09-03 07:45
I'll add a null check to avoid breaking everything

**Comment by NerijusD** [comment] 2018-09-03 08:10
Thank you. I am really looking forward to this fix.

**Comment by aleripe** [comment] 2018-09-03 10:09
Edit committed a few minutes ago

**Comment by NerijusD** [comment] 2018-09-03 10:36
If you want, I can make PR to fix this

**Comment by aleripe** [comment] 2018-09-03 10:37
It should already be fixed... try to download latest version...

**Comment by NerijusD** [comment] 2018-09-03 10:51
Something doesn't look right. Have you published new version? https://www.nuget.org/packages/ReturnTrue.AspNetCore.Identity.Anonymous/

https://www.screencast.com/t/cY0GEGEiVDfH

**Comment by aleripe** [comment] 2018-09-03 10:52
Of course. Maybe it's in a waiting list...

**Closed as completed** 2018-09-19 09:06 UTC
Labels: bug
